export const countries = [
    { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', iso: 'AE' },
    { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', iso: 'SA' },
    { name: 'United States', code: '+1', flag: '🇺🇸', iso: 'US' },
    { name: 'United Kingdom', code: '+44', flag: '🇬🇧', iso: 'GB' },
    { name: 'Canada', code: '+1', flag: '🇨🇦', iso: 'CA' },
    { name: 'Australia', code: '+61', flag: '🇦🇺', iso: 'AU' },
    { name: 'Germany', code: '+49', flag: '🇩🇪', iso: 'DE' },
    { name: 'France', code: '+33', flag: '🇫🇷', iso: 'FR' },
    { name: 'Italy', code: '+39', flag: '🇮🇹', iso: 'IT' },
    { name: 'Spain', code: '+34', flag: '🇪🇸', iso: 'ES' },
    { name: 'Netherlands', code: '+31', flag: '🇳🇱', iso: 'NL' },
    { name: 'India', code: '+91', flag: '🇮🇳', iso: 'IN' },
    { name: 'Pakistan', code: '+92', flag: '🇵🇰', iso: 'PK' },
    { name: 'Bangladesh', code: '+880', flag: '🇧🇩', iso: 'BD' },
    { name: 'Egypt', code: '+20', flag: '🇪🇬', iso: 'EG' },
    { name: 'Jordan', code: '+962', flag: '🇯🇴', iso: 'JO' },
    { name: 'Lebanon', code: '+961', flag: '🇱🇧', iso: 'LB' },
    { name: 'Kuwait', code: '+965', flag: '🇰🇼', iso: 'KW' },
    { name: 'Qatar', code: '+974', flag: '🇶🇦', iso: 'QA' },
    { name: 'Bahrain', code: '+973', flag: '🇧🇭', iso: 'BH' },
    { name: 'Oman', code: '+968', flag: '🇴🇲', iso: 'OM' },
    { name: 'Turkey', code: '+90', flag: '🇹🇷', iso: 'TR' },
    { name: 'China', code: '+86', flag: '🇨🇳', iso: 'CN' },
    { name: 'Japan', code: '+81', flag: '🇯🇵', iso: 'JP' },
    { name: 'South Korea', code: '+82', flag: '🇰🇷', iso: 'KR' },
    { name: 'Singapore', code: '+65', flag: '🇸🇬', iso: 'SG' },
    { name: 'Malaysia', code: '+60', flag: '🇲🇾', iso: 'MY' },
    { name: 'Thailand', code: '+66', flag: '🇹🇭', iso: 'TH' },
    { name: 'Philippines', code: '+63', flag: '🇵🇭', iso: 'PH' },
    { name: 'Indonesia', code: '+62', flag: '🇮🇩', iso: 'ID' },
    { name: 'Vietnam', code: '+84', flag: '🇻🇳', iso: 'VN' },
    { name: 'Brazil', code: '+55', flag: '🇧🇷', iso: 'BR' },
    { name: 'Mexico', code: '+52', flag: '🇲🇽', iso: 'MX' },
    { name: 'Argentina', code: '+54', flag: '🇦🇷', iso: 'AR' },
    { name: 'South Africa', code: '+27', flag: '🇿🇦', iso: 'ZA' },
    { name: 'Nigeria', code: '+234', flag: '🇳🇬', iso: 'NG' },
    { name: 'Kenya', code: '+254', flag: '🇰🇪', iso: 'KE' },
    { name: 'Morocco', code: '+212', flag: '🇲🇦', iso: 'MA' },
    { name: 'Russia', code: '+7', flag: '🇷🇺', iso: 'RU' },
    { name: 'Ukraine', code: '+380', flag: '🇺🇦', iso: 'UA' },
    { name: 'Poland', code: '+48', flag: '🇵🇱', iso: 'PL' },
    { name: 'Sweden', code: '+46', flag: '🇸🇪', iso: 'SE' },
    { name: 'Norway', code: '+47', flag: '🇳🇴', iso: 'NO' },
    { name: 'Denmark', code: '+45', flag: '🇩🇰', iso: 'DK' },
    { name: 'Finland', code: '+358', flag: '🇫🇮', iso: 'FI' },
    { name: 'Switzerland', code: '+41', flag: '🇨🇭', iso: 'CH' },
    { name: 'Austria', code: '+43', flag: '🇦🇹', iso: 'AT' },
    { name: 'Belgium', code: '+32', flag: '🇧🇪', iso: 'BE' },
    { name: 'Ireland', code: '+353', flag: '🇮🇪', iso: 'IE' },
    { name: 'Portugal', code: '+351', flag: '🇵🇹', iso: 'PT' },
    { name: 'Greece', code: '+30', flag: '🇬🇷', iso: 'GR' },
    { name: 'Israel', code: '+972', flag: '🇮🇱', iso: 'IL' },
    { name: 'Iran', code: '+98', flag: '🇮🇷', iso: 'IR' }
];