export const initialProductFormData = {
    rewardTitle: '',
    purchaseQuantity: '',
    rewardDescription: '',
    productId: '',
    templateColor: '#000000',
    loyaltyTemplates: '',
    rewardProductId: '',
    icon1Text: '',
    templateImage: '',
    backgroundImage: '',
    emptyStateImage: '',
    fillStateImage: '',
    icon1: '',
    icon2: '',
    icon3: '',
    logo: '',
    cardId: '',
    price: '',
    bannerTitle: 'product loyalty',
    bannerTitleColor: '#FFFFFF',
};

export const initialPointFormData = {
    rewardTitle: '',
    spendingAmount: '',
    rewardPoints: '',
    rewardPointsEquivalent: '',
    templateColor: '#000000',
    loyaltyTemplates: '',
    icon1Text: '',
    icon2Text: '',
    icon3Text: '',
    templateImage: '',
    icon1: '',
    icon2: '',
    icon3: '',
    logo: '',

    bannerTitle: 'point loyalty',
    bannerTitleColor: '#FFFFFF',
};